name: Deploy Layer

on:
  workflow_dispatch:
    inputs:
      packages:
        required: true
        type: string

      name:
        required: true
        type: string

jobs:
  artifacts:
    runs-on: ubuntu-latest
    container: amazon/aws-lambda-python:3.9

    steps:
      - name: Install CLI tools
        run: yum install -y tar gzip zip

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Layer
        run: |
          pip install ${{ inputs.packages }} --target python
          zip -r layer.zip python

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: layer.zip
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs: artifacts

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.name }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Publish Layer
        run: |
          aws lambda publish-layer-version \
          --layer-name palpiteiro-${{ inputs.name }} \
          --zip-file fileb://layer.zip \
          --description ${{ inputs.packages }} \
          --compatible-runtimes python3.9 \
          --compatible-architectures x86_64