name: Linting

on:
  pull_request:
    branches:
      - main
      - dev
  
jobs:
  linting:
    runs-on: ubuntu-latest
    environment: dev

    strategy:
      fail-fast: false
      matrix:
        path:
          - bigquery_load
          - cartola_matches_extract
          - cartola_matches_transform
          - cartola_players_extract
          - cartola_players_transform
          - cartola_scouts_extract
          - cartola_scouts_transform
          - cartola_squad_extract
          - cartola_squad_transform
          - fivethirtyeight_spi_extract
          - odds_extract
          - odds_transform
          - transfermarkt_extract

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install pylint pytest
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ${{ matrix.path }}

      - name: Lint
        run: pylint ${{ matrix.path }}